Repository flojoy-ai/studio, pull requests merged in 2023-05, with the labels that each got.

#346 Update index.html file
  .prettierignore
  index.html
  public/index.html
Labels: enhancement

#385 Ignore venv folder
  vite.config.ts
Labels: bug-fixed

#400 Fix sidebar issue: missing nodes
  cypress/e2e/04_ctrls_tab_spec.cy.ts
  cypress/e2e/05_user_custom_workflow_spec.cy.ts
  src/AddCTRLBtn.tsx
  src/AddNodeBtn.tsx
  src/App.tsx
  src/__tests__/feature/common/SideBar/Sidebar.test.tsx
  src/__tests__/feature/common/SideBar/__snapshots__/Sidebar.test.tsx.snap
  src/feature/common/Sidebar/Sidebar.tsx
  src/feature/common/Sidebar/SidebarNode.tsx
  src/feature/common/Sidebar/SidebarSection.tsx
  src/feature/controls_panel/manifest/CONTROLS_MANIFEST.ts
  src/feature/flow_chart_panel/components/DefaultNode.tsx
  src/feature/flow_chart_panel/components/NodeWrapper.tsx
  src/feature/flow_chart_panel/components/custom-nodes/ConditionalNode.tsx
  src/feature/flow_chart_panel/components/custom-nodes/SimulationNode.tsx
  src/feature/flow_chart_panel/components/node-edit-menu/NodeEditButtons.tsx
  src/feature/flow_chart_panel/hooks/useAddNewNode.tsx
  src/feature/flow_chart_panel/manifest/COMMANDS_MANIFEST.ts
Labels: bug-fixed

#415 disabled plotly modebar
  package-lock.json
  package.json
  src/__tests__/feature/common/SideBar/__snapshots__/Sidebar.test.tsx.snap
  src/data/manifests_v.1.json
  src/feature/common/PlotlyComponent.tsx
Labels: good first issue, first time UX

#417 Remove associated edges while removing a node
  package-lock.json
  src/feature/flow_chart_panel/components/NodeWrapper.tsx
Labels: bug-fixed

#392 Add table plot to CTRL panel and fix image plot in CTRL panel
  src/App.tsx
  src/__tests__/feature/controls_panel/ControlsTabView.test.tsx
  src/__tests__/feature/controls_panel/views/control-component/ControlComponentState.test.ts
  src/__tests__/feature/flow_chart_panel/components/custom-nodes/VisorNode.test.tsx
  src/__tests__/feature/flow_chart_panel/components/custom-nodes/__snapshots__/VisorNode.test.tsx.snap
  src/__tests__/feature/flow_chart_panel/views/NodeModal.test.tsx
  src/feature/common/PlotlyComponent.tsx
  src/feature/common/usePlotLayout.ts
  src/feature/controls_panel/ControlsTabView.tsx
  src/feature/controls_panel/manifest/CONTROLS_MANIFEST.ts
  src/feature/controls_panel/views/PlotControl.tsx
  src/feature/controls_panel/views/control-component/ControlComponentState.ts
  src/feature/flow_chart_panel/components/DefaultNode.tsx
  src/feature/flow_chart_panel/components/custom-nodes/VisorNode.tsx
  src/feature/flow_chart_panel/components/nodes/3d-scatter.tsx
  src/feature/flow_chart_panel/components/nodes/3d-surface.tsx
  src/feature/flow_chart_panel/components/nodes/Histogram.tsx
  src/feature/flow_chart_panel/components/nodes/Image.tsx
  src/feature/flow_chart_panel/components/nodes/Scatter.tsx
  src/feature/flow_chart_panel/components/nodes/Table.tsx
  src/feature/flow_chart_panel/components/nodes/bar.tsx
  src/feature/flow_chart_panel/components/nodes/box-plot.tsx
  src/feature/flow_chart_panel/components/nodes/line-chart.tsx
  src/feature/flow_chart_panel/svgs/histo-scatter-svg.tsx
  src/feature/flow_chart_panel/views/NodeModal.tsx
  src/feature/results_panel/types/ResultsType.ts
  src/feature/results_panel/views/CustomResultNode.tsx
  src/hooks/usePlotControlEffect.ts
  src/utils/format_plotly_data.ts
Labels: enhancement

#426 Bug fix: clear edges while clearing canvas
  src/feature/flow_chart_panel/components/clear-canvas-btn/ClearCanvasBtn.tsx
Labels: bug-fixed

#435 Fix an issue in PlotlyComponent.tsx
  src/feature/common/PlotlyComponent.tsx
Labels: bug-fixed

#475 Make plotly static on thumbnails
  src/feature/common/PlotlyComponent.tsx
Labels: enhancement

#458 added end node shortcut in sidebar
  package.json
  src/__tests__/feature/common/SideBar/__snapshots__/Sidebar.test.tsx.snap
  src/__tests__/feature/controls_panel/ControlsTabView.test.tsx
  src/__tests__/feature/controls_panel/__snapshots__/ControlsTabView.test.tsx.snap
  src/__tests__/feature/flow_chart_panel/__snapshots__/FlowChartTabView.test.tsx.snap
  src/__tests__/feature/flow_chart_panel/components/NodeWrapper.test.tsx
  src/__tests__/feature/flow_chart_panel/components/SidebarCustomContent.test.tsx
  src/__tests__/feature/flow_chart_panel/components/__snapshots__/NodeWrapper.test.tsx.snap
  src/__tests__/feature/flow_chart_panel/components/__snapshots__/SidebarCustomContent.test.tsx.snap
  src/feature/common/Sidebar/Sidebar.tsx
  src/feature/common/Sidebar/SidebarSection.tsx
  src/feature/flow_chart_panel/FlowChartTabView.tsx
  src/feature/flow_chart_panel/components/RequestNode.tsx
  src/feature/flow_chart_panel/components/SidebarCustomContent.tsx
Labels: enhancement

#487 Moved param type conversion logic to decorator function and added support for boolean param type
  requirements.txt
  src/__tests__/feature/flow_chart_panel/__snapshots__/FlowChartTabView.test.tsx.snap
  src/__tests__/feature/flow_chart_panel/components/NodeWrapper.test.tsx
  src/__tests__/hooks/useControlComponentEffects.test.tsx
  src/data/RECIPES.ts
  src/feature/controls_panel/ControlsTabView.tsx
  src/feature/controls_panel/types/ControlProps.ts
  src/feature/controls_panel/views/KnobCtrl.tsx
  src/feature/controls_panel/views/NodeReference.tsx
  src/feature/controls_panel/views/control-component/ControlComponent.tsx
  src/feature/controls_panel/views/control-component/ControlComponentState.ts
  src/feature/flow_chart_panel/components/node-edit-menu/NodeEditModal.tsx
  src/feature/flow_chart_panel/components/node-edit-menu/ParamField.tsx
  src/feature/flow_chart_panel/hooks/useAddNewNode.tsx
  src/feature/flow_chart_panel/manifest/PARAMETERS_MANIFEST.ts
  src/feature/flow_chart_panel/types/CustomNodeProps.ts
  src/hooks/useFlowChartGraph.ts
  src/hooks/useFlowChartState.ts
Labels: enhancement
